name: carteradb
description: "Mi cartera"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  drift: ^2.19.1+1
  drift_flutter: ^0.1.0
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  image_picker: ^1.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  file_picker: ^8.0.6
  shared_preferences: ^2.3.1
  flutter_iterum: ^0.0.3
  yahoo_finance_data_reader: ^1.0.11
  html: ^0.15.4
  http: ^1.2.2
  # sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.19.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: VictorMono
      fonts:
        - asset: assets/fonts/VictorMono-Regular.ttf
        - asset: assets/fonts/VictorMono-Thin.ttf
